//
// Created by subhuman on 16.01.2022.
//

#ifndef HIGHPERFORMANCE2_CONST_H
#define HIGHPERFORMANCE2_CONST_H

#define BUFFER_SIZE 100
#define PART_ABOVE_TAG 13
#define PART_BELOW_TAG 14
#define RESULT_TAG 15

#endif //HIGHPERFORMANCE2_CONST_H
